[package]
name = "weplay-server"
version = "0.1.0"
authors = ["Hamid R. K. Pishghadam <hamidrkp@riseup.net>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
futures = "0.3.9"
pretty_env_logger = "0.4.0"
